spring:
  datasource:
    url: jdbc:mysql://119.29.22.107:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: Huawei123
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
    max-active: 20
    #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止 ，0时无限制
    max-idle: 8
    max-wait: 100
    #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
    min-idle: 8
    #连接初始值，连接池启动时创建的连接数量的初始值
    initial-size: 20
  mail:
    host: smtp.163.com
    username: aohuanhuanhw@163.com
    password: root123456
    default-encoding: UTF-8